# Generated by Django 4.1.3 on 2022-11-04 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория типа',
                'verbose_name_plural': 'Категории типа',
            },
        ),
        migrations.CreateModel(
            name='ItemTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Название типа')),
                ('photo', models.ImageField(blank=True, upload_to='media/%Y-%m-%d/', verbose_name='Фото категории')),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Тип предмета',
                'verbose_name_plural': 'Типы предмета',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, verbose_name='Название')),
                ('cost', models.CharField(blank=True, max_length=20, verbose_name='Стоимость')),
                ('volume1', models.CharField(blank=True, max_length=20, verbose_name='Первый объём')),
                ('volume2', models.CharField(blank=True, max_length=20, verbose_name='Второй объём')),
                ('volume3', models.CharField(blank=True, max_length=20, verbose_name='Третий объём')),
                ('material1', models.CharField(blank=True, max_length=20, verbose_name='Первый металл')),
                ('material2', models.CharField(blank=True, max_length=20, verbose_name='Второй металл')),
                ('material3', models.CharField(blank=True, max_length=20, verbose_name='Третий металл')),
                ('size1', models.CharField(blank=True, max_length=20, verbose_name='Первый габарит')),
                ('size2', models.CharField(blank=True, max_length=20, verbose_name='Второй габарит')),
                ('size3', models.CharField(blank=True, max_length=20, verbose_name='Третий габарит')),
                ('weight1', models.CharField(blank=True, max_length=20, verbose_name='Первый вес')),
                ('weight2', models.CharField(blank=True, max_length=20, verbose_name='Второй вес')),
                ('weight3', models.CharField(blank=True, max_length=20, verbose_name='Третий вес')),
                ('box1', models.CharField(blank=True, max_length=20, verbose_name='Первая коробка')),
                ('box2', models.CharField(blank=True, max_length=20, verbose_name='Вторая коробка')),
                ('box3', models.CharField(blank=True, max_length=20, verbose_name='Третья коробка')),
                ('cost1_1', models.CharField(blank=True, max_length=20, verbose_name='Первая стоимость от 1 шт.')),
                ('cost1_2', models.CharField(blank=True, max_length=20, verbose_name='Вторая стоимость от 1 шт.')),
                ('cost1_3', models.CharField(blank=True, max_length=20, verbose_name='Третья стоимость от 1 шт.')),
                ('cost100_1', models.CharField(blank=True, max_length=20, verbose_name='Первая стоимость от 100 шт.')),
                ('cost100_2', models.CharField(blank=True, max_length=20, verbose_name='Вторая стоимость от 100 шт.')),
                ('cost100_3', models.CharField(blank=True, max_length=20, verbose_name='Третья стоимость от 100 шт.')),
                ('cost200_1', models.CharField(blank=True, max_length=20, verbose_name='Первая стоимость от 200 шт.')),
                ('cost200_2', models.CharField(blank=True, max_length=20, verbose_name='Вторая стоимость от 200 шт.')),
                ('cost200_3', models.CharField(blank=True, max_length=20, verbose_name='Третья стоимость от 200 шт.')),
                ('material_text', models.CharField(blank=True, max_length=500, verbose_name='Описание материала')),
                ('color_text', models.CharField(blank=True, max_length=500, verbose_name='Цвета')),
                ('cover_text', models.CharField(blank=True, max_length=500, verbose_name='Покрытие')),
                ('box_type_text', models.CharField(blank=True, max_length=500, verbose_name='Тип упаковки')),
                ('tray_text', models.CharField(blank=True, max_length=500, verbose_name='Наличие пепельницы')),
                ('extra_text', models.CharField(blank=True, max_length=500, verbose_name='Дополнительное описание')),
                ('main_photo', models.ImageField(blank=True, upload_to='media/%Y-%m-%d/', verbose_name='Главная фотография')),
                ('photo_color1', models.ImageField(blank=True, upload_to='media/%Y-%m-%d/', verbose_name='Основной цвет')),
                ('photo_color2', models.ImageField(blank=True, upload_to='media/%Y-%m-%d/', verbose_name='Второй цвет')),
                ('photo_color3', models.ImageField(blank=True, upload_to='media/%Y-%m-%d/', verbose_name='Третий цвет')),
                ('photo_color4', models.ImageField(blank=True, upload_to='media/%Y-%m-%d/', verbose_name='Четвёртый цвет')),
                ('photo_color5', models.ImageField(blank=True, upload_to='media/%Y-%m-%d/', verbose_name='Пятый цвет')),
                ('photo_color6', models.ImageField(blank=True, upload_to='media/%Y-%m-%d/', verbose_name='Шестой цвет')),
                ('photo_color7', models.ImageField(blank=True, upload_to='media/%Y-%m-%d/', verbose_name='Седьмой цвет')),
                ('photo_color8', models.ImageField(blank=True, upload_to='media/%Y-%m-%d/', verbose_name='Восьмой цвет')),
                ('tip', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.itemtip', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
    ]
