# Generated by Django 4.1.3 on 2022-11-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtip',
            name='photo',
            field=models.ImageField(blank=True, upload_to='media/%Y-%m-%d/', verbose_name='Фото категории'),
        ),
    ]
